project:
  type: website
  output-dir: docs
  resources: 
    - cv.pdf

website:
  title: "Sarah Ennis"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - education.qmd
      - publications.qmd
      - skills.qmd
      - justforfun.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    page-layout: full

editor: visual

